parameters:
  - in: query
    name: first_name
    schema:
      type: string
    description: The number of items to skip before starting to collect the result set
  - in: query
    name: last_name
    schema:
      type: string
    description: The numbers of items to return